CREATE TABLE
	IF NOT EXISTS `featherpanel_settings` (
		`id` INT NOT NULL AUTO_INCREMENT,
		`name` TEXT NOT NULL,
		`value` TEXT NOT NULL,
		`date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (`id`)
	) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;