CREATE TABLE
	IF NOT EXISTS `featherpanel_servers` (
		`id` int (11) NOT NULL AUTO_INCREMENT,
		`external_id` varchar(191) DEFAULT NULL,
		`uuid` char(36) NOT NULL,
		`uuidShort` char(8) NOT NULL,
		`node_id` int (11) NOT NULL,
		`name` varchar(191) NOT NULL,
		`description` text NOT NULL,
		`status` varchar(191) DEFAULT NULL,
		`skip_scripts` tinyint (1) NOT NULL DEFAULT 0,
		`owner_id` int (11) NOT NULL,
		`memory` int (11) NOT NULL,
		`swap` int (11) NOT NULL,
		`disk` int (11) NOT NULL,
		`io` int (11) NOT NULL,
		`cpu` int (11) NOT NULL,
		`threads` varchar(191) DEFAULT NULL,
		`oom_disabled` tinyint (1) NOT NULL DEFAULT 0,
		`allocation_id` int (11) NOT NULL,
		`realms_id` int (11) NOT NULL,
		`spell_id` int (11) NOT NULL,
		`startup` text NOT NULL,
		`image` varchar(191) NOT NULL,
		`allocation_limit` int (11) DEFAULT NULL,
		`database_limit` int (11) DEFAULT 0,
		`backup_limit` int (11) NOT NULL DEFAULT 0,
		`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
		`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		`installed_at` timestamp NULL DEFAULT NULL,
		PRIMARY KEY (`id`),
		UNIQUE KEY `servers_uuid_unique` (`uuid`),
		UNIQUE KEY `servers_uuidshort_unique` (`uuidShort`),
		UNIQUE KEY `servers_allocation_id_unique` (`allocation_id`),
		UNIQUE KEY `servers_external_id_unique` (`external_id`),
		KEY `servers_node_id_foreign` (`node_id`),
		KEY `servers_owner_id_foreign` (`owner_id`),
		KEY `servers_realm_id_foreign` (`realms_id`),
		KEY `servers_spell_id_foreign` (`spell_id`),
		CONSTRAINT `servers_allocation_id_foreign` FOREIGN KEY (`allocation_id`) REFERENCES `featherpanel_allocations` (`id`),
		CONSTRAINT `servers_spell_id_foreign` FOREIGN KEY (`spell_id`) REFERENCES `featherpanel_spells` (`id`),
		CONSTRAINT `servers_realm_id_foreign` FOREIGN KEY (`realms_id`) REFERENCES `featherpanel_realms` (`id`),
		CONSTRAINT `servers_node_id_foreign` FOREIGN KEY (`node_id`) REFERENCES `featherpanel_nodes` (`id`),
		CONSTRAINT `servers_owner_id_foreign` FOREIGN KEY (`owner_id`) REFERENCES `featherpanel_users` (`id`)
	) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;