CREATE TABLE
    IF NOT EXISTS `featherpanel_nodes` (
        `id` INT(11) NOT NULL AUTO_INCREMENT,
        `uuid` CHAR(36) NOT NULL,
        `public` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 1,
        `name` VARCHAR(191) NOT NULL,
        `description` TEXT DEFAULT NULL,
        `location_id` INT(11) NOT NULL,
        `fqdn` VARCHAR(191) NOT NULL,
        `scheme` VARCHAR(191) NOT NULL DEFAULT 'https',
        `behind_proxy` TINYINT(1) NOT NULL DEFAULT 0,
        `maintenance_mode` TINYINT(1) NOT NULL DEFAULT 0,
        `memory` INT(10) UNSIGNED NOT NULL DEFAULT 1024,
        `memory_overallocate` INT(11) NOT NULL DEFAULT 0,
        `disk` INT(10) UNSIGNED NOT NULL DEFAULT 4096,
        `disk_overallocate` INT(11) NOT NULL DEFAULT 0,
        `upload_size` INT(10) UNSIGNED NOT NULL DEFAULT 100,
        `daemon_token_id` CHAR(16) NOT NULL,
        `daemon_token` TEXT NOT NULL,
        `daemonListen` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 8080,
        `daemonSFTP` SMALLINT(5) UNSIGNED NOT NULL DEFAULT 2022,
        `daemonBase` VARCHAR(191) NOT NULL DEFAULT '/home/daemon-files',
        `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
        `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`),
        UNIQUE KEY `featherpanel_nodes_uuid_unique` (`uuid`),
        UNIQUE KEY `featherpanel_nodes_daemon_token_id_unique` (`daemon_token_id`),
        KEY `featherpanel_nodes_location_id_foreign` (`location_id`),
        CONSTRAINT `featherpanel_nodes_location_id_foreign` FOREIGN KEY (`location_id`) REFERENCES `featherpanel_locations` (`id`) ON DELETE CASCADE
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;