INSERT INTO
	`featherpanel_mail_templates` (
		`id`,
		`name`,
		`subject`,
		`body`,
		`deleted`,
		`locked`,
		`created_at`,
		`updated_at`
	)
VALUES
	(
		1,
		'forgot_password',
		'Reset Your Password',
		'<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Reset Your Password</title></head><body style=\"background-color:#f4f4f4;color:#333;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;line-height:1.6;margin:0;padding:20px\"><div style=\"background-color:#fff;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,.1);margin:0 auto;max-width:600px;overflow:hidden\"><div style=\"background:linear-gradient(135deg,#f093fb 0,#f5576c 100%);color:#fff;padding:40px 30px;text-align:center\"><h1 style=\"font-size:28px;font-weight:600;margin:0 0 10px 0\">Password Reset Request</h1><p style=\"font-size:16px;opacity:.9;margin:0\">We received a request to reset your password</p></div><div style=\"padding:40px 30px\"><div style=\"margin-bottom:30px;text-align:center\"><h2 style=\"color:#2d3748;font-size:24px;margin:0 0 15px 0\">Hello, {first_name} {last_name}</h2><p style=\"color:#4a5568;font-size:16px;line-height:1.6;margin:0\">Someone requested a password reset for your account. If this was you, click the button below to reset your password.</p></div><div style=\"background-color:#f7fafc;border:2px solid #e2e8f0;border-radius:8px;margin:30px 0;padding:30px;text-align:center\"><h3 style=\"color:#2d3748;font-size:20px;margin:0 0 15px 0\">Reset Your Password</h3><p style=\"color:#4a5568;margin:0 0 25px 0\">Click the button below to create a new password for your account.</p><a href=\"{reset_url}\" style=\"background:linear-gradient(135deg,#f093fb 0,#f5576c 100%);border-radius:6px;color:#fff;display:inline-block;font-size:16px;font-weight:600;margin:10px 0;padding:18px 40px;text-decoration:none\">Reset Password</a></div><div style=\"background-color:#fff5f5;border:1px solid #fed7d7;border-radius:6px;margin:30px 0;padding:20px\"><h4 style=\"color:#c53030;font-size:16px;margin:0 0 10px 0\">Security Notice</h4><p style=\"color:#4a5568;font-size:14px;line-height:1.5;margin:0\">If you didn\'t request this password reset, please ignore this email. Your password will remain unchanged. This link will expire in 24 hours for security reasons.</p></div></div><div style=\"background-color:#f7fafc;border-top:1px solid #e2e8f0;padding:30px;text-align:center\"><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">This email was sent to <b>{email}</b></p><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">© 2024-2025 {app_name}. All rights reserved.</p><p style=\"color:#718096;font-size:14px;margin:0\"><a href=\"{support_url}\" style=\"color:#667eea;text-decoration:none\">Support</a></p></div></div></body></html>',
		'false',
		'false',
		'2025-09-22 15:35:21',
		'2025-09-22 15:35:21'
	),
	(
		2,
		'account_created',
		'Welcome to {app_name}!',
		'<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Welcome to {app_name}!</title></head><body style=\"background-color:#f4f4f4;color:#333;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;line-height:1.6;margin:0;padding:20px\"><div style=\"background-color:#fff;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,.1);margin:0 auto;max-width:600px;overflow:hidden\"><div style=\"background:linear-gradient(135deg,#43e97b 0,#38f9d7 100%);color:#fff;padding:40px 30px;text-align:center\"><h1 style=\"font-size:28px;font-weight:600;margin:0 0 10px 0\">Welcome to {app_name}!</h1><p style=\"font-size:16px;opacity:.9;margin:0\">Your account has been created successfully.</p></div><div style=\"padding:40px 30px\"><div style=\"margin-bottom:30px;text-align:center\"><h2 style=\"color:#2d3748;font-size:24px;margin:0 0 15px 0\">Hello, {first_name} {last_name}</h2><p style=\"color:#4a5568;font-size:16px;line-height:1.6;margin:0\">We\'re excited to have you on board. Here are your account details and some tips to get started.</p></div><div style=\"background-color:#f7fafc;border:2px solid #e2e8f0;border-radius:8px;margin:30px 0;padding:30px;text-align:center\"><h3 style=\"color:#2d3748;font-size:20px;margin:0 0 15px 0\">Your Account Details</h3><p style=\"color:#4a5568;margin:0 0 25px 0\"><b>Email:</b>{email}<br><b>Username:</b>{username}</p><p style=\"color:#4a5568;margin:0 0 25px 0\">To get started, log in to your dashboard and explore the features available to you.</p><a href=\"{dashboard_url}\" style=\"background:linear-gradient(135deg,#43e97b 0,#38f9d7 100%);border-radius:6px;color:#fff;display:inline-block;font-size:16px;font-weight:600;margin:10px 0;padding:18px 40px;text-decoration:none\">Go to Dashboard</a></div></div><div style=\"background-color:#f7fafc;border-top:1px solid #e2e8f0;padding:30px;text-align:center\"><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">This email was sent to <b>{email}</b></p><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">© 2024-2025 {app_name}. All rights reserved.</p><p style=\"color:#718096;font-size:14px;margin:0\"><a href=\"{support_url}\" style=\"color:#667eea;text-decoration:none\">Support</a></p></div></div></body></html>',
		'false',
		'false',
		'2025-09-22 15:35:21',
		'2025-09-22 15:35:21'
	),
	(
		3,
		'account_deleted',
		'Your {app_name} Account Has Been Deleted',
		'<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Account Deleted</title></head><body style=\"background-color:#f4f4f4;color:#333;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;line-height:1.6;margin:0;padding:20px\"><div style=\"background-color:#fff;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,.1);margin:0 auto;max-width:600px;overflow:hidden\"><div style=\"background:linear-gradient(135deg,#f5576c 0,#f093fb 100%);color:#fff;padding:40px 30px;text-align:center\"><h1 style=\"font-size:28px;font-weight:600;margin:0 0 10px 0\">Account Deleted</h1><p style=\"font-size:16px;opacity:.9;margin:0\">Your account has been deleted from {app_name}.</p></div><div style=\"padding:40px 30px\"><div style=\"margin-bottom:30px;text-align:center\"><h2 style=\"color:#2d3748;font-size:24px;margin:0 0 15px 0\">Goodbye, {first_name} {last_name}</h2><p style=\"color:#4a5568;font-size:16px;line-height:1.6;margin:0\">We\'re sorry to see you go. Your account and all associated data have been deleted.</p></div></div><div style=\"background-color:#f7fafc;border-top:1px solid #e2e8f0;padding:30px;text-align:center\"><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">This email was sent to <b>{email}</b></p><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">© 2024-2025 {app_name}. All rights reserved.</p><p style=\"color:#718096;font-size:14px;margin:0\"><a href=\"{support_url}\" style=\"color:#667eea;text-decoration:none\">Support</a></p></div></div></body></html>',
		'false',
		'false',
		'2025-09-22 15:35:21',
		'2025-09-22 15:35:21'
	),
	(
		4,
		'server_created',
		'Your Server Has Been Created!',
		'<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Server Created</title></head><body style=\"background-color:#f4f4f4;color:#333;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;line-height:1.6;margin:0;padding:20px\"><div style=\"background-color:#fff;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,.1);margin:0 auto;max-width:600px;overflow:hidden\"><div style=\"background:linear-gradient(135deg,#667eea 0,#764ba2 100%);color:#fff;padding:40px 30px;text-align:center\"><h1 style=\"font-size:28px;font-weight:600;margin:0 0 10px 0\">Server Created</h1><p style=\"font-size:16px;opacity:.9;margin:0\">Your new server is ready!</p></div><div style=\"padding:40px 30px\"><div style=\"margin-bottom:30px;text-align:center\"><h2 style=\"color:#2d3748;font-size:24px;margin:0 0 15px 0\">Hello, {first_name} {last_name}</h2><p style=\"color:#4a5568;font-size:16px;line-height:1.6;margin:0\">Your server<b>{server_name}</b>has been created successfully. Here are the details:</p></div><div style=\"background-color:#f7fafc;border:2px solid #e2e8f0;border-radius:8px;margin:30px 0;padding:30px;text-align:center\"><h3 style=\"color:#2d3748;font-size:20px;margin:0 0 15px 0\">Server Details</h3><p style=\"color:#4a5568;margin:0 0 25px 0\"><b>Server Name:</b>{server_name}<br><b>IP Address:</b>{server_ip}<br><b>Panel URL:</b>{panel_url}</p><p style=\"color:#4a5568;margin:0 0 25px 0\">To manage your server, log in to your dashboard.</p><a href=\"{dashboard_url}\" style=\"background:linear-gradient(135deg,#667eea 0,#764ba2 100%);border-radius:6px;color:#fff;display:inline-block;font-size:16px;font-weight:600;margin:10px 0;padding:18px 40px;text-decoration:none\">Manage Server</a></div></div><div style=\"background-color:#f7fafc;border-top:1px solid #e2e8f0;padding:30px;text-align:center\"><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">This email was sent to <b>{email}</b></p><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">© 2024-2025 {app_name}. All rights reserved.</p><p style=\"color:#718096;font-size:14px;margin:0\"><a href=\"{support_url}\" style=\"color:#667eea;text-decoration:none\">Support</a></p></div></div></body></html>',
		'false',
		'false',
		'2025-09-22 15:35:21',
		'2025-09-22 15:35:21'
	),
	(
		6,
		'server_suspended',
		'Your Server Has Been Suspended',
		'<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Server Suspended</title></head><body style=\"background-color:#f4f4f4;color:#333;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;line-height:1.6;margin:0;padding:20px\"><div style=\"background-color:#fff;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,.1);margin:0 auto;max-width:600px;overflow:hidden\"><div style=\"background:linear-gradient(135deg,#f7971e 0,#ffd200 100%);color:#fff;padding:40px 30px;text-align:center\"><h1 style=\"font-size:28px;font-weight:600;margin:0 0 10px 0\">Server Suspended</h1><p style=\"font-size:16px;opacity:.9;margin:0\">Your server<b>{server_name}</b>has been suspended.</p></div><div style=\"padding:40px 30px\"><div style=\"margin-bottom:30px;text-align:center\"><h2 style=\"color:#2d3748;font-size:24px;margin:0 0 15px 0\">Hello, {first_name} {last_name}</h2><p style=\"color:#4a5568;font-size:16px;line-height:1.6;margin:0\">Your server was suspended due to the following reason:</p></div><div style=\"background-color:#f7fafc;border:2px solid #e2e8f0;border-radius:8px;margin:30px 0;padding:30px;text-align:center\"><p style=\"color:#4a5568;margin:0 0 25px 0\">To resolve this issue, please contact support if needed.</p><a href=\"{support_url}\" style=\"background:linear-gradient(135deg,#f7971e 0,#ffd200 100%);border-radius:6px;color:#fff;display:inline-block;font-size:16px;font-weight:600;margin:10px 0;padding:18px 40px;text-decoration:none\">Contact Support</a></div></div><div style=\"background-color:#f7fafc;border-top:1px solid #e2e8f0;padding:30px;text-align:center\"><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">This email was sent to <b>{email}</b></p><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">© 2024-2025 {app_name}. All rights reserved.</p><p style=\"color:#718096;font-size:14px;margin:0\"><a href=\"{support_url}\" style=\"color:#667eea;text-decoration:none\">Support</a></p></div></div></body></html>',
		'false',
		'false',
		'2025-09-22 15:35:21',
		'2025-09-22 15:35:21'
	),
	(
		7,
		'server_unsuspended',
		'Your Server Has Been Restored',
		'<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Server Unsuspended</title></head><body style=\"background-color:#f4f4f4;color:#333;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;line-height:1.6;margin:0;padding:20px\"><div style=\"background-color:#fff;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,.1);margin:0 auto;max-width:600px;overflow:hidden\"><div style=\"background:linear-gradient(135deg,#38a169 0,#68d391 100%);color:#fff;padding:40px 30px;text-align:center\"><h1 style=\"font-size:28px;font-weight:600;margin:0 0 10px 0\">Server Unsuspended</h1><p style=\"font-size:16px;opacity:.9;margin:0\">Your server<b>{server_name}</b>is now active again.</p></div><div style=\"padding:40px 30px\"><div style=\"margin-bottom:30px;text-align:center\"><h2 style=\"color:#2d3748;font-size:24px;margin:0 0 15px 0\">Hello, {first_name} {last_name}</h2><p style=\"color:#4a5568;font-size:16px;line-height:1.6;margin:0\">Great news! Your server suspension has been lifted and your server is now fully operational.</p></div><div style=\"background-color:#f0fff4;border:2px solid #9ae6b4;border-radius:8px;margin:30px 0;padding:30px;text-align:center\"><h3 style=\"color:#2d3748;font-size:20px;margin:0 0 15px 0\">Server Status</h3><p style=\"color:#4a5568;margin:0 0 25px 0\"><b>Server Name:</b>{server_name}<br><b>Unsuspended At:</b>{unsuspend_time}<br><b>Status:</b><span style=\"color:#38a169;font-weight:600\">Active</span></p><p style=\"color:#4a5568;margin:0 0 25px 0\">Your server is now fully functional and all services have been restored.</p><a href=\"{server_url}\" style=\"background:linear-gradient(135deg,#3182ce 0,#63b3ed 100%);border-radius:6px;color:#fff;display:inline-block;font-size:16px;font-weight:600;padding:12px 30px;text-decoration:none;transition:transform .2s\">Access Server</a></div></div><div style=\"background-color:#f7fafc;border-top:1px solid #e2e8f0;padding:30px;text-align:center\"><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">This email was sent to <b>{email}</b></p><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">© 2024-2025 {app_name}. All rights reserved.</p><p style=\"color:#718096;font-size:14px;margin:0\"><a href=\"{support_url}\" style=\"color:#667eea;text-decoration:none\">Support</a></p></div></div></body></html>',
		'false',
		'false',
		'2025-09-22 15:35:21',
		'2025-09-22 15:35:21'
	),
	(
		8,
		'server_deleted',
		'Your Server Has Been Deleted',
		'<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Server Deleted</title></head><body style=\"background-color:#f4f4f4;color:#333;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;line-height:1.6;margin:0;padding:20px\"><div style=\"background-color:#fff;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,.1);margin:0 auto;max-width:600px;overflow:hidden\"><div style=\"background:linear-gradient(135deg,#e53e3e 0,#fc8181 100%);color:#fff;padding:40px 30px;text-align:center\"><h1 style=\"font-size:28px;font-weight:600;margin:0 0 10px 0\">Server Deleted</h1><p style=\"font-size:16px;opacity:.9;margin:0\">Your server<b>{server_name}</b>has been permanently deleted.</p></div><div style=\"padding:40px 30px\"><div style=\"margin-bottom:30px;text-align:center\"><h2 style=\"color:#2d3748;font-size:24px;margin:0 0 15px 0\">Hello, {first_name} {last_name}</h2><p style=\"color:#4a5568;font-size:16px;line-height:1.6;margin:0\">Your server has been permanently deleted from our system.</p></div><div style=\"background-color:#fed7d7;border:2px solid #feb2b2;border-radius:8px;margin:30px 0;padding:30px;text-align:center\"><h3 style=\"color:#2d3748;font-size:20px;margin:0 0 15px 0\">Deletion Details</h3><p style=\"color:#4a5568;margin:0 0 25px 0\"><b>Server Name:</b>{server_name}<br><b>Deleted At:</b>{deletion_time}<br></p><p style=\"color:#4a5568;margin:0 0 25px 0\">All data associated with this server has been permanently removed and cannot be recovered.</p></div></div><div style=\"background-color:#f7fafc;border-top:1px solid #e2e8f0;padding:30px;text-align:center\"><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">This email was sent to <b>{email}</b></p><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">© 2024-2025 {app_name}. All rights reserved.</p><p style=\"color:#718096;font-size:14px;margin:0\"><a href=\"{support_url}\" style=\"color:#667eea;text-decoration:none\">Support</a></p></div></div></body></html>',
		'false',
		'false',
		'2025-09-22 15:35:21',
		'2025-09-22 15:35:21'
	),
	(
		9,
		'account_suspended',
		'Your {app_name} Account Has Been Suspended',
		'<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Account Suspended</title></head><body style=\"background-color:#f4f4f4;color:#333;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;line-height:1.6;margin:0;padding:20px\"><div style=\"background-color:#fff;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,.1);margin:0 auto;max-width:600px;overflow:hidden\"><div style=\"background:linear-gradient(135deg,#d69e2e 0,#f6e05e 100%);color:#fff;padding:40px 30px;text-align:center\"><h1 style=\"font-size:28px;font-weight:600;margin:0 0 10px 0\">Account Suspended</h1><p style=\"font-size:16px;opacity:.9;margin:0\">Your account has been temporarily suspended.</p></div><div style=\"padding:40px 30px\"><div style=\"margin-bottom:30px;text-align:center\"><h2 style=\"color:#2d3748;font-size:24px;margin:0 0 15px 0\">Hello, {first_name} {last_name}</h2><p style=\"color:#4a5568;font-size:16px;line-height:1.6;margin:0\">Your account has been suspended due to a violation of our terms of service.</p></div><div style=\"background-color:#fffbeb;border:2px solid #fed7aa;border-radius:8px;margin:30px 0;padding:30px;text-align:center\"><h3 style=\"color:#2d3748;font-size:20px;margin:0 0 15px 0\">Suspension Details</h3><p style=\"color:#4a5568;margin:0 0 25px 0\"><b>Suspended At:</b>{suspension_time}<br><b>Account Status:</b><span style=\"color:#d69e2e;font-weight:600\">Suspended</span></p><p style=\"color:#4a5568;margin:0 0 25px 0\">To appeal this suspension or resolve the issue, please contact our support team.</p><a href=\"{support_url}\" style=\"background:linear-gradient(135deg,#3182ce 0,#63b3ed 100%);border-radius:6px;color:#fff;display:inline-block;font-size:16px;font-weight:600;padding:12px 30px;text-decoration:none;transition:transform .2s\">Appeal Suspension</a></div></div><div style=\"background-color:#f7fafc;border-top:1px solid #e2e8f0;padding:30px;text-align:center\"><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">This email was sent to <b>{email}</b></p><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">© 2024-2025 {app_name}. All rights reserved.</p><p style=\"color:#718096;font-size:14px;margin:0\"><a href=\"{support_url}\" style=\"color:#667eea;text-decoration:none\">Support</a></p></div></div></body></html>',
		'false',
		'false',
		'2025-09-22 15:35:21',
		'2025-09-22 15:35:21'
	),
	(
		10,
		'account_unsuspended',
		'We revoked your suspension!',
		'<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Account Unsuspended</title></head><body style=\"background-color:#f4f4f4;color:#333;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Oxygen,Ubuntu,Cantarell,sans-serif;line-height:1.6;margin:0;padding:20px\"><div style=\"background-color:#fff;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,.1);margin:0 auto;max-width:600px;overflow:hidden\"><div style=\"background:linear-gradient(135deg,#38a169 0,#68d391 100%);color:#fff;padding:40px 30px;text-align:center\"><h1 style=\"font-size:28px;font-weight:600;margin:0 0 10px 0\">Account Restored</h1><p style=\"font-size:16px;opacity:.9;margin:0\">Your account suspension has been lifted.</p></div><div style=\"padding:40px 30px\"><div style=\"margin-bottom:30px;text-align:center\"><h2 style=\"color:#2d3748;font-size:24px;margin:0 0 15px 0\">Welcome back, {first_name} {last_name}</h2><p style=\"color:#4a5568;font-size:16px;line-height:1.6;margin:0\">Great news! Your account suspension has been lifted and you now have full access to all services.</p></div><div style=\"background-color:#f0fff4;border:2px solid #9ae6b4;border-radius:8px;margin:30px 0;padding:30px;text-align:center\"><h3 style=\"color:#2d3748;font-size:20px;margin:0 0 15px 0\">Account Status</h3><p style=\"color:#4a5568;margin:0 0 25px 0\"><b>Unsuspended At:</b>{unsuspension_time}<br><b>Account Status:</b><span style=\"color:#38a169;font-weight:600\">Active</span></p><p style=\"color:#4a5568;margin:0 0 25px 0\">You can now access all features and services. Thank you for your patience during the review process.</p><a href=\"{dashboard_url}\" style=\"background:linear-gradient(135deg,#3182ce 0,#63b3ed 100%);border-radius:6px;color:#fff;display:inline-block;font-size:16px;font-weight:600;padding:12px 30px;text-decoration:none;transition:transform .2s\">Access Dashboard</a></div></div><div style=\"background-color:#f7fafc;border-top:1px solid #e2e8f0;padding:30px;text-align:center\"><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">This email was sent to <b>{email}</b></p><p style=\"color:#718096;font-size:14px;margin:0 0 10px 0\">© 2024-2025 {app_name}. All rights reserved.</p><p style=\"color:#718096;font-size:14px;margin:0\"><a href=\"{support_url}\" style=\"color:#667eea;text-decoration:none\">Support</a></p></div></div></body></html>',
		'false',
		'false',
		'2025-09-22 15:35:21',
		'2025-09-22 15:35:21'
	);